### ISSUE TITLE
Help to compile client

### ISSUE THREAD

**Issue by atao** [maldevel/gdog#6]
Hello,

I need some help to compile client...

Thanks

**Comment by maldevel** [comment]
How a python script is related to compilation?

**Comment by atao** [comment]
When i test client.py it's work very well, but after compilation, i have this message when i run the client.exe

`C:\Python27\Scripts>build\client\client.exe
Error loading Python DLL: C:\Python27\Scripts\build\client\python27.dll (error code 126)`


Compilation is ok but not exe not work...

`C:\Python27\Scripts>pyinstaller.exe gdog-master\client.py
96 INFO: PyInstaller: 3.2.1
96 INFO: Python: 2.7.13
97 INFO: Platform: Windows-10-10.0.14393
99 INFO: wrote C:\Python27\Scripts\client.spec
100 INFO: UPX is not available.
101 INFO: Extending PYTHONPATH with paths
['C:\\Python27\\Scripts\\gdog-master', 'C:\\Python27\\Scripts']
101 INFO: checking Analysis
105 INFO: Building because inputs changed
106 INFO: Initializing module dependency graph...
109 INFO: Initializing module graph hooks...
167 INFO: running Analysis out00-Analysis.toc
169 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
256 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
257 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
258 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
342 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9247_none ...
343 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35.manifest
344 INFO: Searching for file msvcr90.dll
344 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcr90.dll
345 INFO: Searching for file msvcp90.dll
346 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcp90.dll
346 INFO: Searching for file msvcm90.dll
347 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcm90.dll
427 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
429 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
429 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
430 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
507 INFO: Caching module hooks...
511 INFO: Analyzing C:\Python27\Scripts\gdog-master\client.py
2037 INFO: Processing pre-safe import module hook   _xmlplus
2163 INFO: Processing pre-safe import module hook   win32com
2849 INFO: Processing pre-find module path hook   distutils
3613 INFO: Loading module hooks...
3614 INFO: Loading module hook "hook-distutils.py"...
3615 INFO: Loading module hook "hook-xml.py"...
3686 INFO: Loading module hook "hook-httplib.py"...
3687 INFO: Loading module hook "hook-pywintypes.py"...
3921 INFO: Loading module hook "hook-encodings.py"...
                                                                   4501 INFO: Loading module hook "hook-win32com.py"...
4578 INFO: Loading module hook "hook-pythoncom.py"...
4802 INFO: Looking for ctypes DLLs
4817 INFO: Analyzing run-time hooks ...
4821 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
4827 INFO: Looking for dynamic libraries
5075 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.1_none_7dd1e0ebd6590e0b.manifest
5076 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
5157 INFO: Searching for assembly x86_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
5157 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c.manifest
5160 INFO: Searching for file mfc90.dll
5160 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90.dll
5160 INFO: Searching for file mfc90u.dll
5161 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfc90u.dll
5161 INFO: Searching for file mfcm90.dll
5161 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90.dll
5161 INFO: Searching for file mfcm90u.dll
5161 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_4bf7e3e2bf9ada4c\mfcm90u.dll
5239 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.1_none_7dd1e0ebd6590e0b.manifest
5240 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_ed01d9e4fb230e88.manifest
5241 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
5821 INFO: Looking for eggs
5822 INFO: Using Python library C:\WINDOWS\system32\python27.dll
5822 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9247), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b')]
5825 INFO: Warnings written to C:\Python27\Scripts\build\client\warnclient.txt
5888 INFO: checking PYZ
5901 INFO: checking PKG
5903 INFO: Building because C:\Python27\Scripts\build\client\client.exe.manifest changed
5903 INFO: Building PKG (CArchive) out00-PKG.pkg
5956 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
5960 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
5961 INFO: checking EXE
5963 INFO: Rebuilding out00-EXE.toc because pkg is more recent
5964 INFO: Building EXE from out00-EXE.toc
5965 INFO: Appending archive to EXE C:\Python27\Scripts\build\client\client.exe
6017 INFO: Building EXE from out00-EXE.toc completed successfully.
6025 INFO: checking COLLECT
WARNING: The output directory "C:\Python27\Scripts\dist\client" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
13618 INFO: Removing dir C:\Python27\Scripts\dist\client
13634 INFO: Building COLLECT out00-COLLECT.toc
13685 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
14228 INFO: Building COLLECT out00-COLLECT.toc completed successfully.`

**Comment by atao** [comment]
It's works!

With this command : pyinstaller.exe --onefile --windowed gdog-master\client.py

Good!
