### ISSUE TITLE
imaplib.error: Lookup failed

### ISSUE THREAD

**Issue by TheBlackBaken** [maldevel/gdog#7]
Hello;
I'm currently trying to run the script (gdog.py) but i'm already getting this error.

File "gdog.py", line 306, in <module>
    gdog = Gdog()
  File "gdog.py", line 123, in __init__
    self.c.login(gmail_user, gmail_pwd)
  File "/usr/lib/python2.7/imaplib.py", line 520, in login
    raise self.error(dat[-1])
imaplib.error: Lookup failed f26mb392779289eda

Can you help me.
Thank you in advance.

**Comment by TheBlackBaken** [comment]
Hello, 

Just for informations, I fixed the error.

**Comment by n-nathaniel** [comment]
How did you Solve?

**Comment by athul-das** [comment]
How did you solve this? 
I got this error when I send more than 5 emails, seems wierd doesnt have any issue earlier.
